project:
  type: website
  
website:
  title: ""
  page-navigation: true
  sidebar: 
    style: floating
    search: true
    contents:
      - href: index.qmd
        text: Home
        
      # - section: "Basics"
      #   contents:
      #     - index.qmd
          
      - section: "Cursos"
        contents:
          -  section: "Introdução ao R"
             contents: 
              - href: Cursos/Introducao_R/Cadernos/1-Apresentacao_R_Rstudio.qmd
                text: "Apresentação do R e Rstudio"
              - href: Cursos/Introducao_R/Cadernos/2-Estrutura_de_dados.qmd
                text: Estruturas de dados
              - href: Cursos/Introducao_R/Cadernos/3-Estruturas_de_Controle.qmd 
                text: Estruturas de Controles
              - href: Cursos/Introducao_R/Cadernos/4-Funcoes.qmd 
                text: Funções
              - href: Cursos/Introducao_R/Cadernos/5-Funcoes_Prob.qmd 
                text: Funções de Probabilidades
                
               
          -  section: "Probabilidade e Estatística"
             contents:
              - href: Cursos/Probabilidade_Estatistica/Cadernos/1-Conceitos_Iniciais.qmd
                text: "Conceitos Iniciais"
              - href: Cursos/Probabilidade_Estatistica/Cadernos/2-Tecnicas_de_Amostragem.qmd  
                text: "Técnicas de Amostragem"
              - href: Cursos/Probabilidade_Estatistica/Cadernos/3-Tabelas_Graficos.qmd  
                text: "Tabelas e Gráficos"
              - href: Cursos/Probabilidade_Estatistica/Cadernos/4-Medidas_Posicao.qmd 
                text: "Medidas de Posição e Separatrizes"
              - href: Cursos/Probabilidade_Estatistica/Cadernos/5-Medidas_de_Dispersao.qmd 
                text: "Medidas de Dispersão"
          
            

# website:
#   title: "leonardo-site"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - about.qmd
#       - href: 
#         text: A

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

revealjs:
  output-ext: "slides.html"
  # showNotes: true
  # controls: true
  # pdf-separate-fragments: true
  # slide-number: true
  # pdf-max-pages-per-slide: true
  