project:
  type: website
  
website:
  title: ""
  page-navigation: true
  sidebar: 
    style: floating
    search: true
    contents:
      - href: index.qmd
        text: Home
        
      # - section: "Basics"
      #   contents:
      #     - index.qmd
          
      - section: "Cursos"
        contents:
          -  section: "Introdução ao R"
             contents: 
              - href: Cursos/Introducao_R/Cadernos/1-Apresentacao_R_Rstudio.qmd
                text: "Apresentação do R e Rstudio"
              - href: Cursos/Introducao_R/Cadernos/2-Estrutura_de_dados.qmd
                text: Estrutura de dados
          -  section: "Probabilidade e Estatística"
             contents:
              - href: Cursos/Probabilidade_Estatistica/Cadernos/Conceitos_Iniciais.qmd
                text: "Conceitos Iniciais"
               
          
              


# website:
#   title: "leonardo-site"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - about.qmd
#       - href: 
#         text: A

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

revealjs:
  output-ext: "slides.html"
  # showNotes: true
  # controls: true
  # pdf-separate-fragments: true
  # slide-number: true
  # pdf-max-pages-per-slide: true
  